import Foundation

struct EnStrings {
    static let map: [String: String] = [
        "app_name": "Bosi Store",
        "products": "Products",
        "cart": "Cart",
        "profile": "Profile",
        "search": "Search products...",
        "add_to_cart": "Add to Cart",
        "added_to_cart": "Added to Cart",
        "remove": "Remove",
        "clear_cart": "Clear All",
        "checkout": "Checkout",
        "total": "Total",
        "subtotal": "Subtotal",
        "savings": "Your Savings",
        "payable": "Payable Amount",
        "discount": "OFF",
        "about": "About Product",
        "colors": "Available Colors",
        "free_ship": "Free Shipping",
        "return_policy": "14-Day Return",
        "authentic": "Authentic",
        "reviews": "Reviews",
        "write_review": "Write a Review",
        "add_photo": "Add Photo",
        "add_video": "Add Video",
        "submit_review": "Submit Review",
        "rating": "Rating",
        "login": "Login",
        "register": "Register",
        "email": "Email",
        "password": "Password",
        "confirm_pass": "Confirm Password",
        "full_name": "Full Name",
        "phone": "Phone Number",
        "login_sub": "Welcome back to Bosi shopping",
        "register_sub": "Create your account",
        "no_account": "Don't have an account?",
        "has_account": "Already have an account?",
        "logout": "Logout",
        "settings": "Settings",
        "language": "Language",
        "addresses": "Addresses",
        "add_address": "Add Address",
        "street": "Street Address",
        "city": "City",
        "state": "State",
        "zip": "Zip Code",
        "country": "Country",
        "use_location": "Use Current Location",
        "save_address": "Save Address",
        "empty_cart": "Your cart is empty",
        "empty_cart_sub": "Add your favorite products",
        "featured": "Featured Products",
        "special": "Special Offers",
        "complete_buy": "Complete Purchase",
        "confirm_buy": "Confirm purchase for",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "review_hint": "Share your experience...",
        "no_reviews": "No reviews yet",
        "first_review": "Be the first to review",
        "pass_mismatch": "Passwords do not match",
        "fill_fields": "Please fill all fields",
        "invalid_cred": "Invalid email or password",
        "reg_success": "Registration successful!",
        "welcome": "Welcome",
        "edit_profile": "Edit Profile",
        "address_title": "Address Title",
        "location": "Location",
        "lat": "Latitude",
        "lng": "Longitude",
        "delete": "Delete",
        "items": "items",
        "qty": "Qty",
        "terms": "Terms & Conditions",
        "privacy": "Privacy Policy",
        "accept_terms": "I accept the",
        "and": "and",
        "terms_error": "You must accept the terms and conditions to register.",
        "terms_content": "By registering and using the Bosi Store app, you agree to abide by our store policies. All products are guaranteed to be authentic. Returns are accepted within 14 days of purchase provided the item is in its original condition. The store reserves the right to cancel any order in case of pricing errors or inventory issues.",
        "privacy_content": "We take your privacy and security very seriously. All your personal data, including your location, addresses, and contact information, are securely stored locally on your device in this version. We do not share, sell, or distribute your personal information to any third parties. Your data remains strictly confidential and protected.",
        "danger_zone": "Danger Zone",
        "delete_account": "Delete Account",
        "delete_confirm_title": "Are you sure?",
        "delete_confirm_msg": "This action cannot be undone. All your data and addresses will be permanently deleted.",
    ]
}
